### ISSUE TITLE
Enum private

### ISSUE THREAD

**Issue by Chnapy** [ScreachFr/Timeflies_ChatServer#1]
Dans Channel.java t'as la fonction public ConnectionStatus connectUser(User u).
Or l'énum ConnectionStatus est privée. T'as donc une fonction public qui renvoie un objet private.
Du coup si une classe extérieur appele cette fonction, elle ne pourra pas utiliser l'objet renvoyer.

Solution: rend la fonction private OU l'énum public.

**Comment by agaspardcilia** [comment]
Mais je te ressure, ya plein de problèmes dans ce genre là. J'ai mis le dev du chat en pause pour me concentrer sur l'auth. Si tu regardes le code de près c'est blindé d'incohérence et de bugs. Quand j'aurais fini de m'occuper de l'auth, le chat n'aura plus tous ces problèmes.
Tout ça mis à part, merci d'avoir inauguré la section "issues", ça va être plus qu'utile.

**Comment by agaspardcilia** [comment]
L'enum est maintenant public même si je pense qu'elle sera supprimé dans peut de temps histoire de centraliser les états possible. En effet pour l'instant je constate de la redondance.
